# Generated by Django 2.2.16 on 2023-05-31 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230526_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-add_date'], 'verbose_name': 'favorite'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='recipesingredient',
            options={'verbose_name': 'amount ingredient in recipe'},
        ),
        migrations.AlterModelOptions(
            name='recipestag',
            options={'verbose_name': 'tags in recipe'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'shopping cart'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='add date'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.RecipesIngredient', to='recipes.Ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(blank='True', related_name='recipes', through='recipes.RecipesTag', to='recipes.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='recipestag',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes', verbose_name='recipe'),
        ),
    ]
